application: fear-con
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: static/images

- url: /stylesheets
  static_dir: static/stylesheets

- url: .*
  script: main.py
  

