application: fear-con
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: static/images

- url: /stylesheets
  static_dir: static/stylesheets
  
- url: /js
  static_dir: static/js

- url: /update
  script: update.py
  
- url: /user/(.*)
  script: user.py

- url: .*
  script: main.py
  

